/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness: the process is up. Never touches dependencies.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readyz
     * @description Readiness: report each dependency separately so a partial outage is visible.
     */
    get: operations["readyz_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signup */
    post: operations["signup_v1_auth_signup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_v1_members_get"];
    put?: never;
    /** Create Member */
    post: operations["create_member_v1_members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/members/{membership_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_v1_members__membership_id__delete"];
    options?: never;
    head?: never;
    /** Update Member Role */
    patch: operations["update_member_role_v1_members__membership_id__patch"];
    trace?: never;
  };
  "/v1/me/mfa/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mfa Start */
    post: operations["mfa_start_v1_me_mfa_start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/mfa/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mfa Confirm */
    post: operations["mfa_confirm_v1_me_mfa_confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Api Keys */
    get: operations["list_api_keys_v1_api_keys_get"];
    put?: never;
    /** Create Api Key */
    post: operations["create_api_key_v1_api_keys_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/api-keys/{key_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Api Key */
    delete: operations["revoke_api_key_v1_api_keys__key_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/audit-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Audit Logs */
    get: operations["list_audit_logs_v1_audit_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations["list_products_v1_products_get"];
    put?: never;
    /** Create Product */
    post: operations["create_product_v1_products_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations["get_product_v1_products__product_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Product */
    patch: operations["update_product_v1_products__product_id__patch"];
    trace?: never;
  };
  "/v1/products/{product_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Versions */
    get: operations["list_versions_v1_products__product_id__versions_get"];
    put?: never;
    /** Create Version */
    post: operations["create_version_v1_products__product_id__versions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/product-versions/{version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Version */
    get: operations["get_version_v1_product_versions__version_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Version */
    patch: operations["update_version_v1_product_versions__version_id__patch"];
    trace?: never;
  };
  "/v1/product-versions/{version_id}/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Upload */
    post: operations["request_upload_v1_product_versions__version_id__uploads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/files/download-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Request Download */
    get: operations["request_download_v1_files_download_url_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/product-versions/{version_id}/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Files */
    get: operations["list_files_v1_product_versions__version_id__files_get"];
    put?: never;
    /** Complete Upload */
    post: operations["complete_upload_v1_product_versions__version_id__files_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/files/{file_id}/pages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List File Pages */
    get: operations["list_file_pages_v1_files__file_id__pages_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/product-versions/{version_id}/analyses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Analysis */
    post: operations["submit_analysis_v1_product_versions__version_id__analyses_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/dead-letters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Dead Letters */
    get: operations["list_dead_letters_v1_analyses_dead_letters_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/dead-letters/{dead_letter_id}/replay": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replay Dead Letter */
    post: operations["replay_dead_letter_v1_analyses_dead_letters__dead_letter_id__replay_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/{analysis_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Analysis */
    get: operations["get_analysis_v1_analyses__analysis_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/{analysis_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Analysis Events
     * @description JSON history by default; a Server-Sent Events live stream (P5-T5)
     *     when the client asks for `text/event-stream` - the same path, per
     *     IMPLEMENTATION.md §7's API table, rather than a second endpoint.
     *     `response_model=None` (unlike every other route here): the return type
     *     is a union including `StreamingResponse`, which isn't a valid Pydantic
     *     field - FastAPI still returns a `StreamingResponse` byte-for-byte as
     *     given and JSON-encodes the list in the other branch via its default
     *     `jsonable_encoder`, so nothing about the actual response shape changes.
     */
    get: operations["list_analysis_events_v1_analyses__analysis_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/{analysis_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Analysis */
    post: operations["cancel_analysis_v1_analyses__analysis_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/{analysis_id}/findings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Findings */
    get: operations["list_findings_v1_analyses__analysis_id__findings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/findings/{finding_id}/evidence": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Finding Evidence */
    get: operations["get_finding_evidence_v1_findings__finding_id__evidence_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/{analysis_id}/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Reports */
    get: operations["list_reports_v1_analyses__analysis_id__reports_get"];
    put?: never;
    /** Generate Report */
    post: operations["generate_report_v1_analyses__analysis_id__reports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/reports/{report_id}/pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Render Report Pdf
     * @description §16 names PDF rendering as its own queue - when a real Arq pool is
     *     configured, this enqueues `app.reports.worker.render_report_pdf_job` and
     *     returns 202 immediately (poll `GET /v1/analyses/{id}/reports` for the
     *     resulting `kind="pdf"` row); with no pool configured (local/test
     *     default, mirroring `submit_analysis`'s own fallback), it renders inline
     *     and returns the finished row with 201.
     */
    post: operations["render_report_pdf_v1_reports__report_id__pdf_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/reports/{report_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Report */
    get: operations["get_report_v1_reports__report_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnalysisOut */
    AnalysisOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Product Version Id
       * Format: uuid
       */
      product_version_id: string;
      state: components["schemas"]["AnalysisState"];
      confidence_tier: components["schemas"]["ConfidenceTier"] | null;
      /** Failure Stage */
      failure_stage: string | null;
      /** Retryable */
      retryable: boolean | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Finished At */
      finished_at: string | null;
      /** Progress Percentage */
      progress_percentage: number;
      /** Total Tokens In */
      total_tokens_in: number;
      /** Total Tokens Out */
      total_tokens_out: number;
      /** Total Cost Cents */
      total_cost_cents: number;
    };
    /**
     * AnalysisState
     * @enum {string}
     */
    AnalysisState:
      | "queued"
      | "validating"
      | "preprocessing"
      | "ocr"
      | "extracting"
      | "verifying_evidence"
      | "normalizing"
      | "classifying"
      | "rule_eval"
      | "scoring"
      | "needs_review"
      | "review"
      | "completed"
      | "failed"
      | "cancelled";
    /** ApiKeyCreateRequest */
    ApiKeyCreateRequest: {
      /** Name */
      name: string;
      /** @default analyst */
      role: components["schemas"]["Role"];
    };
    /** ApiKeyCreatedOut */
    ApiKeyCreatedOut: {
      /** Key */
      key: string;
      api_key: components["schemas"]["ApiKeyOut"];
    };
    /** ApiKeyOut */
    ApiKeyOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Prefix */
      prefix: string;
      role: components["schemas"]["Role"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Revoked At */
      revoked_at: string | null;
    };
    /** AuditLogOut */
    AuditLogOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Action */
      action: string;
      /** Actor Type */
      actor_type: string;
      /** Actor Id */
      actor_id: string | null;
      /** Actor Label */
      actor_label: string | null;
      /** Resource Type */
      resource_type: string | null;
      /** Resource Id */
      resource_id: string | null;
      /** Ip */
      ip: string | null;
      /** Correlation Id */
      correlation_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * AvStatus
     * @enum {string}
     */
    AvStatus: "pending" | "clean" | "infected" | "skipped" | "error";
    /** CompleteUploadRequest */
    CompleteUploadRequest: {
      /** Key */
      key: string;
      /** Filename */
      filename: string;
    };
    /**
     * ConfidenceTier
     * @enum {string}
     */
    ConfidenceTier: "high" | "medium" | "low";
    /** DeadLetterOut */
    DeadLetterOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Analysis Id
       * Format: uuid
       */
      analysis_id: string;
      /** Stage */
      stage: string;
      reason: components["schemas"]["DeadLetterReason"];
      /** Error Message */
      error_message: string;
      /** Attempt Count */
      attempt_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Replayed At */
      replayed_at: string | null;
      /** Replayed As Analysis Id */
      replayed_as_analysis_id: string | null;
    };
    /**
     * DeadLetterReason
     * @enum {string}
     */
    DeadLetterReason: "stage_exhausted" | "permanent_error" | "timeout" | "stalled";
    /** DownloadResponse */
    DownloadResponse: {
      /** Url */
      url: string;
      /** Expires In */
      expires_in: number;
    };
    /** EvidenceDetailOut */
    EvidenceDetailOut: {
      /**
       * Extracted Field Id
       * Format: uuid
       */
      extracted_field_id: string;
      /** Field Path */
      field_path: string;
      /**
       * Evidence Span Id
       * Format: uuid
       */
      evidence_span_id: string;
      /**
       * File Page Id
       * Format: uuid
       */
      file_page_id: string;
      /** Page No */
      page_no: number;
      /** Bbox */
      bbox: [number, number, number, number];
      /** Text Snippet */
      text_snippet: string;
      /** Source */
      source: string;
      /** Page Image Url */
      page_image_url: string;
      /** Page Image Expires In */
      page_image_expires_in: number;
    };
    /** EvidenceRefOut */
    EvidenceRefOut: {
      /**
       * Extracted Field Id
       * Format: uuid
       */
      extracted_field_id: string;
      /**
       * Evidence Span Id
       * Format: uuid
       */
      evidence_span_id: string;
    };
    /** FileOut */
    FileOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Product Version Id
       * Format: uuid
       */
      product_version_id: string;
      /** Original Filename */
      original_filename: string;
      /** Mime */
      mime: string;
      /** Bytes */
      bytes: number;
      /** Page Count */
      page_count: number | null;
      status: components["schemas"]["FileStatus"];
      av_status: components["schemas"]["AvStatus"];
      /** Rejection Reason */
      rejection_reason: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** FilePageOut */
    FilePageOut: {
      /** Page No */
      page_no: number;
      /** Width */
      width: number;
      /** Height */
      height: number;
      /** Render Key */
      render_key: string;
    };
    /**
     * FileStatus
     * @enum {string}
     */
    FileStatus: "uploading" | "validating" | "ready" | "rejected";
    /** FindingOut */
    FindingOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Analysis Id
       * Format: uuid
       */
      analysis_id: string;
      /** Rule Key */
      rule_key: string;
      /** Rule Version */
      rule_version: number;
      status: components["schemas"]["FindingStatus"];
      severity: components["schemas"]["Severity"];
      /** Message */
      message: string | null;
      /** Details */
      details: {
        [key: string]: unknown;
      };
      /** Confidence */
      confidence: number;
      /** Evidence Refs */
      evidence_refs: components["schemas"]["EvidenceRefOut"][];
    };
    /**
     * FindingStatus
     * @enum {string}
     */
    FindingStatus: "pass" | "fail" | "insufficient_data" | "not_applicable";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Totp Code */
      totp_code?: string | null;
      /** Recovery Code */
      recovery_code?: string | null;
    };
    /** LoginResponse */
    LoginResponse: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Org Id */
      org_id: string | null;
      /** Csrf Token */
      csrf_token: string;
      /**
       * Mfa Required
       * @default false
       */
      mfa_required: boolean;
    };
    /** MeResponse */
    MeResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      status: components["schemas"]["UserStatus"];
      /** Mfa Enabled */
      mfa_enabled: boolean;
      /** Active Org Id */
      active_org_id: string | null;
      role: components["schemas"]["Role"] | null;
      /** Capabilities */
      capabilities: string[];
      /** Memberships */
      memberships: components["schemas"]["MembershipOut"][];
      /** Csrf Token */
      csrf_token?: string | null;
    };
    /** MemberCreateRequest */
    MemberCreateRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      role: components["schemas"]["Role"];
      /** Password */
      password: string;
      /**
       * Display Name
       * @default
       */
      display_name: string;
    };
    /** MemberOut */
    MemberOut: {
      /**
       * Membership Id
       * Format: uuid
       */
      membership_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      role: components["schemas"]["Role"];
      status: components["schemas"]["MembershipStatus"];
    };
    /** MemberRoleUpdateRequest */
    MemberRoleUpdateRequest: {
      role: components["schemas"]["Role"];
    };
    /** MembershipOut */
    MembershipOut: {
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Organization Name */
      organization_name: string;
      role: components["schemas"]["Role"];
      status: components["schemas"]["MembershipStatus"];
    };
    /**
     * MembershipStatus
     * @enum {string}
     */
    MembershipStatus: "active" | "invited" | "revoked";
    /** MfaEnrolConfirmRequest */
    MfaEnrolConfirmRequest: {
      /** Totp Code */
      totp_code: string;
    };
    /** MfaEnrolConfirmResponse */
    MfaEnrolConfirmResponse: {
      /** Recovery Codes */
      recovery_codes: string[];
    };
    /** MfaEnrolStartResponse */
    MfaEnrolStartResponse: {
      /** Secret */
      secret: string;
      /** Otpauth Uri */
      otpauth_uri: string;
    };
    /** ProductCreateRequest */
    ProductCreateRequest: {
      /** Name */
      name: string;
      /** Internal Sku */
      internal_sku: string;
      /** Category Hint */
      category_hint?: string | null;
      /** Market Codes */
      market_codes?: string[];
    };
    /** ProductOut */
    ProductOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Internal Sku */
      internal_sku: string;
      /** Category Hint */
      category_hint: string | null;
      /** Market Codes */
      market_codes: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProductUpdateRequest */
    ProductUpdateRequest: {
      /** Name */
      name?: string | null;
      /** Category Hint */
      category_hint?: string | null;
    };
    /** ProductVersionOut */
    ProductVersionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Version No */
      version_no: number;
      /** Label */
      label: string;
      status: components["schemas"]["ProductVersionStatus"];
      /** Locked At */
      locked_at: string | null;
      /** Superseded At */
      superseded_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ProductVersionStatus
     * @enum {string}
     */
    ProductVersionStatus: "draft" | "locked" | "superseded";
    /** ReportOut */
    ReportOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Analysis Id
       * Format: uuid
       */
      analysis_id: string;
      /** Kind */
      kind: string;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Sha256 */
      sha256: string;
      /** Pdf Key */
      pdf_key: string | null;
      /** Pdf Download Url */
      pdf_download_url: string | null;
      /** Pdf Download Expires In */
      pdf_download_expires_in: number | null;
      /** Snapshot */
      snapshot: {
        [key: string]: unknown;
      };
    };
    /**
     * Role
     * @enum {string}
     */
    Role: "owner" | "admin" | "reviewer" | "analyst" | "viewer";
    /**
     * Severity
     * @enum {string}
     */
    Severity: "critical" | "major" | "minor" | "advisory";
    /**
     * SignupRequest
     * @description Bootstraps a new organization together with its Owner.
     */
    SignupRequest: {
      /** Organization Name */
      organization_name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /**
       * Display Name
       * @default
       */
      display_name: string;
    };
    /** UploadRequest */
    UploadRequest: {
      /** Filename */
      filename: string;
      /** Content Type */
      content_type: string;
    };
    /** UploadResponse */
    UploadResponse: {
      /** Key */
      key: string;
      /** Upload Url */
      upload_url: string;
      /** Expires In */
      expires_in: number;
    };
    /**
     * UserStatus
     * @enum {string}
     */
    UserStatus: "active" | "disabled";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VersionCreateRequest */
    VersionCreateRequest: {
      /**
       * Label
       * @default
       */
      label: string;
    };
    /** VersionUpdateRequest */
    VersionUpdateRequest: {
      /** Label */
      label: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  signup_v1_auth_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  list_members_v1_members_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"][];
        };
      };
    };
  };
  create_member_v1_members_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_member_v1_members__membership_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        membership_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_member_role_v1_members__membership_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        membership_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberRoleUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mfa_start_v1_me_mfa_start_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MfaEnrolStartResponse"];
        };
      };
    };
  };
  mfa_confirm_v1_me_mfa_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MfaEnrolConfirmRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MfaEnrolConfirmResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_api_keys_v1_api_keys_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKeyOut"][];
        };
      };
    };
  };
  create_api_key_v1_api_keys_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKeyCreatedOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_api_key_v1_api_keys__key_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_audit_logs_v1_audit_logs_get: {
    parameters: {
      query?: {
        action?: string | null;
        resource_type?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditLogOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_products_v1_products_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"][];
        };
      };
    };
  };
  create_product_v1_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_product_v1_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_product_v1_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_versions_v1_products__product_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductVersionOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_version_v1_products__product_id__versions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductVersionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_version_v1_product_versions__version_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductVersionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_version_v1_product_versions__version_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductVersionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_upload_v1_product_versions__version_id__uploads_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_download_v1_files_download_url_get: {
    parameters: {
      query: {
        key: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DownloadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_files_v1_product_versions__version_id__files_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_upload_v1_product_versions__version_id__files_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteUploadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_file_pages_v1_files__file_id__pages_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        file_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FilePageOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_analysis_v1_product_versions__version_id__analyses_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_dead_letters_v1_analyses_dead_letters_get: {
    parameters: {
      query?: {
        unreplayed_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeadLetterOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  replay_dead_letter_v1_analyses_dead_letters__dead_letter_id__replay_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dead_letter_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_analysis_v1_analyses__analysis_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_analysis_events_v1_analyses__analysis_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_analysis_v1_analyses__analysis_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_findings_v1_analyses__analysis_id__findings_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["FindingStatus"] | null;
        severity?: components["schemas"]["Severity"] | null;
      };
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindingOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_finding_evidence_v1_findings__finding_id__evidence_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        finding_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EvidenceDetailOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reports_v1_analyses__analysis_id__reports_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_report_v1_analyses__analysis_id__reports_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  render_report_pdf_v1_reports__report_id__pdf_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_report_v1_reports__report_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
